module.exports =[
  {
    user_id: '1',
    user_password: '123456',
    user_first_name:'jessica',
    user_last_name:'liu',
    user_email:'jessica@parktime.com',
    user_type: 'walker',
    user_postal_code:'m2e 2i8',
    user_address:'100 king st.',
    user_unit_number:'20',
    user_city: 'toronto',
    user_province: 'ontario',
    user_country:'canada',
    user_phone:'416-999-9999',
    user_picture:'http://knexjs.org/assets/images/knex.png',
    user_latitude: 43.653112,
    user_longitude: -79.390700,
    user_description:'I love dogs',
    user_deleted_at: null
  },

  { 
    user_id: '2',
    user_password: '123456',
    user_first_name:'garima',
    user_last_name:'arya',
    user_email:'garima@parktime.com',  
    user_type: 'walker',
    user_postal_code:'M8H 5M6',
    user_address:'120 king st.',
    user_unit_number:'12',
    user_city: 'toronto',
    user_province: 'ontario',
    user_country:'canada',
    user_phone:'416-909-7899',
    user_picture:'http://webneel.com/daily/sites/default/files/images/project/TiagoHoisel-3d-character-design.preview.jpg',
    user_latitude: 43.932112,
    user_longitude: -79.490700,
    user_description:"I love dogs and i'm very comfortable with them",
    user_deleted_at: null
  },

  {
    user_id: '3',
    user_password: '123456',
    user_first_name:'shubham',
    user_last_name:'arya',
    user_email:'shubham@parktime.com',
    user_type: 'walker',
    user_postal_code:'M5A0H6',
    user_address:'132 Berkley st.',
    user_unit_number:'323',
    user_city: 'toronto',
    user_province: 'ontario',
    user_country:'canada',
    user_phone:'647-909-7896',
    user_picture:'https://thumbs.dreamstime.com/b/funny-cartoon-raccoon-19551786.jpg',
    user_latitude: 43.353112,
    user_longitude: -79.390700,
    user_description:"I love dogs and i'm very comfortable with them",
    user_deleted_at: null
  },

  { 
    user_id: '4',
    user_password: '123456',
    user_first_name:'sagar',
    user_last_name:'sharma',
    user_email:'sagar@parktime.com',
    user_type: 'owner',
    user_postal_code:'M5A0H6',
    user_address:'132 Berkley st.',
    user_unit_number:'346',
    user_city: 'toronto',
    user_province: 'ontario',
    user_country:'canada',
    user_phone:'647-779-7896',
    user_picture:'https://img3.stockfresh.com/files/t/tigatelu/m/21/2874561_stock-photo-funny-cow-cartoon-embrace-a-bottle-of-milk.jpg',
    user_latitude: 43.673112,
    user_longitude: -79.380700,
    user_description:"looking for a long term dog walker",
    user_deleted_at: null
  },

  { 
    user_id: '5',
    user_password: '123456',
    user_first_name:'kanika',
    user_last_name:'sharma',
    user_email:'kanika@parktime.com',
    user_type: 'walker',
    user_postal_code:'M5B0C7',
    user_address:'33 yonge st.',
    user_unit_number:'146',
    user_city: 'toronto',
    user_province: 'ontario',
    user_country:'canada',
    user_phone:'417-009-7886',
    user_picture:'https://akamai-platform.foxfilm.com/s3/production/201701/ba2cb7e8bd4cdba2a16dc1163d2517969c902d5a.jpg',
    user_latitude: 43.983112,
    user_longitude: -79.590700,
    user_description:"responsible, loving, patient",
    user_deleted_at: null
  },
  { 
    user_id: '6',
    user_password: '123456',
    user_first_name:'Tati',
    user_last_name:'Westbrook',
    user_email:'tati@parktime.com',
    user_type: 'owner',
    user_postal_code:'M1B5K7',
    user_address:'Old Finch Avenue',
    user_unit_number:'361A',
    user_city: 'toronto',
    user_province: 'ontario',
    user_country:'canada',
    user_phone:'416-009-1286',
    user_picture:'https://akamai-platform.foxfilm.com/s3/production/201701/ba2cb7e8bd4cdba2a16dc1163d2517969c902d5a.jpg',
    user_latitude: 43.883112,
    user_longitude: -79.700700,
    user_description:"owner of three bichons",
    user_deleted_at: null
  },
  { 
    user_id: '7',
    user_password: '123456',
    user_first_name:'Jeffree',
    user_last_name:'Star',
    user_email:'Jeffree@parktime.com',
    user_type: 'owner',
    user_postal_code:'M4M2J8',
    user_address:'167 Boulton Ave.',
    user_unit_number:'',
    user_city: 'toronto',
    user_province: 'ontario',
    user_country:'canada',
    user_phone:'416-898-7886',
    user_picture:'https://akamai-platform.foxfilm.com/s3/production/201701/ba2cb7e8bd4cdba2a16dc1163d2517969c902d5a.jpg',
    user_latitude: 43.123112,
    user_longitude: -79.190700,
    user_description:"home to husky Ryan",
    user_deleted_at: null
  },
  { 
    user_id: '8',
    user_password: '123456',
    user_first_name:'Jaclyn',
    user_last_name:'Hill',
    user_email:'jh@parktime.com',
    user_type: 'walker',
    user_postal_code:'M4A1C4',
    user_address:'80 Bartley Dr.',
    user_unit_number:'',
    user_city: 'toronto',
    user_province: 'ontario',
    user_country:'canada',
    user_phone:'416-229-9842',
    user_picture:'https://akamai-platform.foxfilm.com/s3/production/201701/ba2cb7e8bd4cdba2a16dc1163d2517969c902d5a.jpg',
    user_latitude: 43.983112,
    user_longitude: -79.590700,
    user_description:"I love dogs and i'm very comfortable with them",
    user_deleted_at: null
  },
  { 
    user_id: '9',
    user_password: '123456',
    user_first_name:'James',
    user_last_name:'Austin',
    user_email:'james@parktime.com',
    user_type: 'owner',
    user_postal_code:'M3C0C6',
    user_address:'181 Wynford Dr',
    user_unit_number:'',
    user_city: 'toronto',
    user_province: 'ontario',
    user_country:'canada',
    user_phone:'416-129-7886',
    user_picture:'https://akamai-platform.foxfilm.com/s3/production/201701/ba2cb7e8bd4cdba2a16dc1163d2517969c902d5a.jpg',
    user_latitude: 43.983112,
    user_longitude: -79.590700,
    user_description:"looking for a dog walker",
    user_deleted_at: null
  },
  { 
    user_id: '10',
    user_password: '123456',
    user_first_name:'Emma',
    user_last_name:'Stone',
    user_email:'emma@parktime.com',
    user_type: 'walker',
    user_postal_code:'M6P1H9',
    user_address:'10 Kenneth Ave',
    user_unit_number:'',
    user_city: 'toronto',
    user_province: 'ontario',
    user_country:'canada',
    user_phone:'416-224-2386',
    user_picture:'https://akamai-platform.foxfilm.com/s3/production/201701/ba2cb7e8bd4cdba2a16dc1163d2517969c902d5a.jpg',
    user_latitude: 43.983112,
    user_longitude: -79.590700,
    user_description:"your dog's best friend",
    user_deleted_at: null
  }

]
